sudo: required

language: java

services:
  - docker

jdk:
  - openjdk8

env:
  global:
    - secure: "oiowIIbjLfXEwtfUTtwvZE8QTHqjBrluj/jGx06sVQZKhH4wfI0nVsSfPoWQn2pj2ijmavGoeqbblyRP9rw9ArQGFqY6lDBVh78gd+T2geGaZs4k7DMjysRHjXK9gdrKVhpXDpXrchw9zEi/rMut6nJdVQyPwcTSoLsgoECltbahIyEW6DLFl9Uv4ML6m1sv80jyqEMcf/lIys8sE2BQp/bKVrNCT2FvszxVG8sby8Ql2QU5cyBXstU0COLcjITO3+3imCsOxnNy8mNJbFCctuLM4gN0eKEogVsQbUd42tWGrUsJslDkf+cqG8hM4V6y2glA8KH5GU8lezbTrEIxYcS4m/pLC7OoO1adA1N9oP913ZNJcxi9YGdPfElggjeAdf+qsA2Jl92+wmJ/TO473RuxPOObHPYcbwvgV1Fd76yWmAeJDWbHgchqmOpS8zrnbB73Sg5n31sF4paPFMS9mKCYJNqGLs+NL88ZEp831ScLZkeZlCpJ3UHwkpPh7q1h+IVlabrDV7aJNRORAANZOxWPVFXWuCkQoiL1lN+YRLSzdaToa6AHKtl4xw2waMd9LHGR7Uv0tqsoiMUbLw48mVAZb4ta/Iee4mPnM2KIxm8yAfZCmZE0Jg9eiJx2UsntZqCo0xbd5+SOXzv6ryUD7gpvZ6cMrSwVOsMiI4sAV/8="
    - # ^^ DOCKER_USERNAME
    - secure: "CsMMLxFdiGrQOohWY5CTAEj4GQFdtsvrmGHPjferBUKM4jCrEtbYu6iltNPivb+ZZrZ/E6KdDrGZ71253/dXlbIyG/gTfFc+QM5sVVKDfDaLxEqOtb2muqORKlC0zxRlEqeaOSK7Pc/lKdjYVLCseh3UQIqyQhP1ONPGGYyEoz7EfeVX3qciFp74wc5BQPoB5k90+XQ4VzxkRKido3HGWmWxB3zFyZ8VhA2BeXdnOg82LJYcrxKXM6uz4Qtazd+hji1qksurTNV4KGkwh39ayCn9Y2jYC99wSE8XumkTrOCRGzNmXfMjt7wSowHUxzZ3ZIZaUsO1/gEWr9rmrrlQzZ8N/wx8sAeMYcZPtXNCbWakLCU0hYbmTJ9OfMcUFc7S+ynhOcaiUJdn8iwu+gULbZ1e1TRHZ5xHGCr/Z58cK6fpsd7uR7mUSwAfwj7S87s3qPYi8Pd7ny0T5I039qoA5j3C4XTy8ikV3WQihksQxwXyDO3axmwIYJrR0dJmAUY7TnAKMcsWv4EX0IjS41qy08XEvhh0HuRN+M/s3aBFr/BfUkMyJUmZPl2LXL8p8MW8FnMT8Zaa5GoXFBiYhUFPFXIYUqM+0K27DtYFkxr2UvEZ5Q4wrgidQCknCCPiJHzg99j1tPp2izHCPXms495nvKfcs0X74IFeP4XGtNI/Brw="
    - # ^^ DOCKER_PASSWORD

install:
  - mvn install -Dmaven.javadoc.skip=true

after_success:
  docker build -t netshoes/sample-sleuth-notification:latest -t netshoes/sample-sleuth-notification:1.0-SNAPSHOT .

deploy:
  provider: script
  script: bash src/main/bash/docker_push.sh
  on:
    branch: master

cache:
  directories:
    - ~/.m2/repository